# Conexión a Azure SQL (Tecnología Propietaria)
spring.datasource.url=jdbc:sqlserver://servidor-cheques-ruddy.database.windows.net:1433;database=SistemaChequesDB;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=adminRuddy
spring.datasource.password=yvubPbzVUgXhJmRcnT7H
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Puerto para Render (se inyecta automáticamente, pero lo definimos por si acaso)
server.port=${PORT:8080}